name: Build and deploy image to ECR (AWS)

on:

  push:
    branches: [master]

jobs:
  build_deploy:
    runs-on: ubuntu-latest


    env:

      AWS_REGION: eu-west-3
      ECR_REGISTRY: 992382591031.dkr.ecr.eu-west-3.amazonaws.com/iberialuxuryimages129
      ECR_REPOSITORY: iberiaimage
     

    steps:
      - name: Checkout code

        uses: actions/checkout@v3
      
      - name: Debug AWS secrets
        run: |
          echo "AWS_ACCESS_KEY_ID is set: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY is set: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
      

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t ${{ env.ECR_REPOSITORY }}:latest .

      - name: Tag Docker image for ECR
        run: docker tag ${{ env.ECR_REPOSITORY }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest